//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KozmetickiClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kozmetickisalonEntities : DbContext
    {
        public kozmetickisalonEntities()
            : base("name=kozmetickisalonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<artikl> artikl { get; set; }
        public virtual DbSet<artiklsalon> artiklsalon { get; set; }
        public virtual DbSet<kategorija> kategorija { get; set; }
        public virtual DbSet<nabava> nabava { get; set; }
        public virtual DbSet<nabavaartikl> nabavaartikl { get; set; }
        public virtual DbSet<proizvodac> proizvodac { get; set; }
        public virtual DbSet<salon> salon { get; set; }
        public virtual DbSet<salonusluga> salonusluga { get; set; }
        public virtual DbSet<smjena> smjena { get; set; }
        public virtual DbSet<usluga> usluga { get; set; }
        public virtual DbSet<zaposlenik> zaposlenik { get; set; }
        public virtual DbSet<zaposlenikusluga> zaposlenikusluga { get; set; }
        public virtual DbSet<dobavljac> dobavljac { get; set; }
        public virtual DbSet<adresa> adresa { get; set; }
        public virtual DbSet<grad> grad { get; set; }
        public virtual DbSet<narudzba> narudzba { get; set; }
    }
}
