//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace KozmetickiClassLibrary
{
    using System;
    using System.Collections.Generic;


    public partial class nabava
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nabava()
        {
            this.nabavaartikl = new HashSet<nabavaartikl>();
        }
    
        public int idnabava { get; set; }
        public int idsalon { get; set; }
        public int iddobavljac { get; set; }
        public System.DateTime datum { get; set; }
        public decimal ukupnaCijena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nabavaartikl> nabavaartikl { get; set; }
        public virtual salon salon { get; set; }
        public virtual dobavljac dobavljac { get; set; }
    }
}
